name: Deploy frontend website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client
        env:
          CLIENT_DEPLOY_URL: ${{ secrets.CLIENT_DEPLOY_URL }}
        run: |
          curl -X POST $CLIENT_DEPLOY_URL --fail